import Head from "next/head";
import Home from "../components/Home";

export default function App() {
  return (
    <div>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home />
    </div>
  );
}

// export async function getServerSideProps(context) {
//   const request = await fetch(
//     `https://api.themoviedb.org/3${requests.fetchNetflixOriginals}`
//   ).then((response) => response.json());

//   return {
//     props: {
//       results: request.results,
//     },
//   };
// }
